homebrew:
  taps:
    - homebrew/cask
    - homebrew/core
  packages:
    - name: ansible
    - name: bash-completion
    - name: docker
    - name: git
    - name: jq
    - name: tree
    - name: vim
    - name: wget
    - name: snyk
    - name: fish
    - name: gnu-tar
    - name: zsh-syntax-highlighting
    # Erlang build tool
    - name: kerl
    - name: tmux
    - name: reattach-to-user-namespace

  cask:
    - name: appcleaner
    - name: cyberduck
    - name: docker
    - name: google-cloud-sdk
    - name: google-japanese-ime
    #- name: skitch
    - name: startninja
    #- name: station
    #- name: visual-studio-code
    - name: vagrant
    - name: virtualbox
    # corretto jdk
    - name: corretto
    - name: corretto8
    - name: corretto11
    # adopt open jdk
    - name: adoptopenjdk
    - name: adoptopenjdk8
    # Microsoft Open JDK
    - name: microsoft-openjdk
    - name: microsoft-openjdk11

dotfiles:
  - .bash_profile
  - .bashrc
  - .zprofile
  - .zshrc
  - .profile
  - .profile.anyenv
  - .profile.software
  - .tmux.conf
  - .dockerrc

anyenv:
  - name: pyenv
    legacy: no
    global: 3.10.0
    versions:
      - 3.10.0
  - name: nodenv
    legacy: no
    global: 16.13.0
    versions:
      - 16.13.0
      - 17.0.1
  - name: goenv
    legacy: no
    global: 1.17.0
    versions:
      - 1.17.0
  - name: rbenv
    legacy: no
    global: 3.0.2
    versions:
      - 2.5.0
      - 2.7.4
      - 3.0.2
  - name: erlenv
    legacy: yes
    global: 24.2
    versions:
      - 24.2
  - name: exenv
    legacy: yes
    global: 1.13.1
    versions:
      - 1.13.1
  - name: tfenv
    legacy: yes
    global: 1.1.2
    versions:
      - 1.1.2
  - name: jenv
    legacy: yes
    global: openjdk64-13.0.1
    versions:
      - ""
  - name: sbtenv
    legacy: no
    global: sbt-1.1.1
    versions:
      - sbt-1.1.1

sdkman:
  global: 7.3.3
  gradle_versions:
    - 6.9.2
    - 7.3.3
