---
- block:
  - name: update homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes

  - name: homebrew tap
    homebrew_tap:
      name: '{{ item }}'
      state: present
    with_items: '{{ homebrew.taps }}'

  - name: install homebrew packages
    homebrew:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
    with_items: '{{ homebrew.packages }}'

  tags:
    - homebrew